### ISSUE TITLE
[Request] PowerMeterClass

### ISSUE THREAD

**Issue by Adminius** [berni2288/OpenDTU_PowerLimiter#3]
### Describe the solution you'd like

Aktuell sind PowerMeter Values aus MQTT sind direkt in PowerLimiter class.
Um andere Power-Quellen zu ermöglichen, macht es aus meiner Sicht Sinn eine PowerMeter Klasse zu erstellen die wiederum die Daten von möglichen Quellen bereithält/abfragt/sammelt:
- MQTT
- SDM-Stromzähler über RS485 (bin gerade dabei es einzubauen)
- HTTP/Json (es gab schon requests dazu)
- ???

Dafür müsste auch UI ein wenig anders gestaltet werden:
Quelle für die Leistung soll in eigenes Menü-Unterpunkt wandern, wo man entsprechend die Quelle auswählt und die Parameter zu der Quelle:
- MQTT: 3 Einzelleistungen pro Phase (wobei es nur 1ph reichen sollte)
- SDM-Zähler: Pins für UART-RS485 Adapter, SDM Adresse, (evtl.: bitrate, parity und stopbit?)

**Comment by berni2288** [comment]
Hört sich gut an.
Also HTTP und Json support wär wahrscheinlich nicht so schwer zu bewerkstelligen. Mit der Eingabe eines custom Jsonpath könnte man einen Wert gezielt aus einer Json response auslesen, das wär dann relativ flexibel.

Ich hab nur mittlerweile Angst dass die Größe von der Firmware bald 100% erreicht, bin schon bei 91% :) Vielleicht müsste man mit conditional #includes arbeiten damit man nur das compiled was man braucht.

**Comment by Adminius** [comment]
Mit MQTT und SDM Zähler bin ich quasi fertig.
Nur die UI macht mich noch fertig.
Platz ist noch da.

**Comment by berni2288** [comment]
> Und ich meine, ich habe einen Fehler gefunden: Leistung darf auch negativ sein, also int statt uint:
> 
> https://github.com/berni2288/OpenDTU_PowerLimiter/blob/a703334379ee6f305c649c2faab398703a8e5c7f/src/PowerLimiter.cpp#L149

Ja das sollte denke ich auf signed geändert werden :) Nicht dass es dann auf einmal 65535 ist.

**Comment by Adminius** [comment]
Genau das war ja mein Problem 🤣 
Ich habe dann gleich auf int32 gestellt, 32768 Watt können bei großem Verbrauch (z.B. eAuto laden) erreicht werden...

**Comment by berni2288** [comment]
Neues repo: https://github.com/helgeerbe/OpenDTU-OnBattery

Siehe: https://github.com/berni2288/OpenDTU_PowerLimiter/discussions/4#discussioncomment-4960797
